[package]
name = "open_depacker"
version = "0.2.2"
authors = ["Daniel Collin <daniel@collin.com>"]
edition = "2021"

[build-dependencies]
cc = "1.0"
walkdir = "2"

[dependencies]
clap = { version = "3.1.7", features = ["derive"] }
rayon = "1.5"
walkdir = "2"
sha2 = "0.9.2"
