[package]
name = "open_depacker"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]

[dependencies]
lazy_static = "0.1.*"
byteorder = "0.4"
combine = "2.2.0"
musashi = { path = "musashi" }

[dependencies.clap]
version = "1"
features = [ "suggestions", "color" ]
