[package]
name = "open_depacker"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]
build = "build.rs"

[dependencies]
lazy_static = "0.1.*"
byteorder = "0.4"
musashi = { path = "../musashi" } 

[dependencies.clap]
version = "1"
features = [ "suggestions", "color" ]
